### ISSUE TITLE
람쥐님이 구현한 회원가입 페이지로 연결 안되는 문제

### ISSUE THREAD

**Issue by biyamn** [letty-project/letty-client#12]
dev 브랜치에서 실행한 코드의 결과입니다.
로그인 버튼 클릭시 회원가입 페이지로 이동하지 않는 문제가 발생하고 있고 수정이 필요해보입니다.
![xmdnlxj](https://github.com/letty-project/letty-client/assets/101965666/ef0bb7fe-bebc-4200-9d18-ce6b131676bb)

**Comment by cottonpup** [comment]
저희 머지 충돌했던 거 지금 커밋해놨습니다! 저희 제일 문제는 공통 컴포넌트 부분인 헤더를 똑같이 만들어야하는 거 같아요. 목요일에 같이 의논해보아요.
