### ISSUE TITLE
2023년 10월 27일 미팅

### ISSUE THREAD

**Issue by biyamn** [letty-project/letty-client#17]
TODO
- [x] 피그마 확인 후 페이지별 작업
  - [x] 람쥐: 회원가입 페이지
  - [x] 쥑: 작가 글쓰기 페이지

STUDY
- [ ] TypeScript
- [ ] React Router
- [ ] 공부 과정나 겪은 이슈 디코에 즉각 올리기

**Comment by cottonpup** [comment]
# 배운 점
- 테일윈드 @apply 커스텀 CSS
- flex-shrink -> flex 공부 다시하기 ㅠㅠ
- 리액트 라우터에서 useHistory 훅은 없어지고 useNavigate 가 생김
